version: '3.6'
services:
  redis:
    image: "redis:alpine"
    hostname: redis
    container_name: clients-hunter-redis
    ports:
      - "6379:6379"

  bot:
    build: ./bot
    image: "clients-hunter-bot:latest"
    container_name: clients-hunter-bot
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_JOBS_CHANNEL=FILTERED_JOBS

  filter:
    build: ./filter
    image: "clients-hunter-filter:latest"
    container_name: clients-hunter-filter
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RAW_JOBS_CHANNEL=RAW_JOBS
      - FILTERED_JOBS_CHANNEL=FILTERED_JOBS

  parser:
    build: ./parser
    image: "clients-hunter-parser:latest"
    container_name: clients-hunter-parser
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_CHANNEL=RAW_JOBS
